### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by BenMKT** [SnakyMz/Catalog_of_my_things#29]
There are 3 people in our team project as follows:
- Team member 1 is @mhnazary 
- Team member 2 is @BenMKT 
- Team member 3 is @SnakyMz 

[Link to the project](https://github.com/SnakyMz/Catalog_of_my_things/projects/1)

**Comment by codepantha** [comment]
# STATUS: APPROVED 🟢 ✔️ 

Hi team 👋,

Your project is complete!  There is nothing else to say other than... it's time to start building :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/2RGhmKXcl0ViM/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
